language: node_js
node_js:
- 6.11.0
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - sudo pip install -r requirements.txt
before_script:
  - wget "http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - (yarn)
  - (yarn start &)
  - sleep 10
script:
  - yarn test
  - pybot test.robot
  - yarn run build
  - yarn test:size
after_script:
  - cp -Rv build docs
  - ls -al docs/
  - yarn outdated
notifications:
  email:
    - stollenwerk@kitconcept.com
    - fernandezdealba@kitconcept.com
